#######################################
# Website
#######################################


lang: fr
from: markdown+emoji
filters:
  - iconify
project:
  type: website
  render:
  - index.qmd
  - resources.qmd
  - cours/index.qmd
  - cours/SVD.qmd
  - cours/ACP.qmd
  - cours/AFC.qmd
  - cours/ACM.qmd
  - cours/AFM.qmd
  - cours/presentation.qmd
  - td/1_ACP/TD.qmd
  - td/2_ACM/TD.qmd
  - td/3_AFM/TD.qmd
  - tp/index.qmd
  - tp/markdown.qmd
  - tp/quarto.qmd
  post-render: assets/make-pdf.sh


website:
  bread-crumbs: false
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Statistical Exploration"
  site-url: https://bcharlier.github.io/KMAK7AC1/
  repo-url: https://github.com/bcharlier/KMAK7AC1
  repo-actions: [source, issue]
  search:
    location: navbar
    type: textbox
  navbar:
    title: KMAK7AC1
    background: primary
    search: true
    left:
      - sidebar:Cours
      - sidebar:TD
      - sidebar:TP
      - sidebar:Quarto
    right:
      - text: "{{<iconify simple-icons:moodle title='Moodle'>}}"
        href: https://moodle.utoulouse.fr/
        aria-label: Moodle
      - text: "{{< iconify simple-icons:github title='GitHub'>}}"
        href: https://github.com/bcharlier/KMAK7AC1
        aria-label: GitHub
  sidebar:

    - id: Cours
      collapse-level: 3
      contents: 
        - cours/presentation.qmd
        - cours/SVD.qmd
        - cours/ACP.qmd
        - cours/AFC.qmd
        - cours/ACM.qmd
        - cours/AFM.qmd

    - id: TD
      collapse-level: 3
      contents:
        - td/1_ACP/TD.qmd
        - td/2_ACM/TD.qmd
        - td/3_AFM/TD.qmd
    
    - id: TP
      collapse-level: 3
      contents:
        - tp/index.qmd
    
    - id: Quarto
      collapse-level: 2
      contents:
        - tp/markdown.qmd
        - tp/quarto.qmd
    
    - id: Réferences
      contents:
        - resources.qmd


format:
  html:
    theme: 
      - lux
      - assets/custom.scss
    css:
      - assets/table.css
      - assets/print-clean.css
    include-in-header:
      - assets/unfold-panel.html
    html-math-method: katex
    number-sections: true
    toc-depth: 3
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-responsive: true
    fig.align: center
    reference-location: margin
    citation-location: margin
    from: markdown+emoji

    #toc-location: right
    #toc: true

  revealjs:
    theme: assets/metropolis.scss
    css: assets/table.css
    width: 1024
    height: 768
    slide-level: 2
    slide-number: true
    progress: true
    history: false
    toc: true
    toc-depth: 1
    code-line-numbers: false
    eval: true
    echo: true

execute:
  freeze: auto
  cache: false

knitr:
  opts_chunk:
    prompt: true
    message: false
    warning: false