#######################################
# Website
#######################################


lang: fr
from: markdown+emoji
filters:
  - iconify
project:
  type: website
  render:
  - index.qmd
  - resources.qmd
  - cours/index.qmd
  - cours/SVD.qmd
  - cours/ACP.qmd
  - cours/AFC.qmd
  - cours/ACM.qmd
  - cours/AFM.qmd
  - cours/presentation.qmd
  - td/1_ACP/TD.qmd
  - td/2_ACM/TD.qmd
  - td/3_AFM/TD.qmd
  - tp/index.qmd
  - tp/0_quarto/markdown.qmd
  - tp/0_quarto/quarto.qmd
  - tp/1_ACP/TP.qmd
  - tp/2_AFC-ACM/TP.qmd

  post-render: assets/make-pdf.sh


website:
  bread-crumbs: false
  back-to-top-navigation: true
  page-navigation: true # true not working in website
  title: "Statistical Exploration"
  site-url: https://bcharlier.github.io/KMAK7AC1/
  repo-url: https://github.com/bcharlier/KMAK7AC1
  repo-actions: [source, issue]
  search:
    location: navbar
    type: textbox
  navbar:
    title: KMAK7AC1
    background: primary
    search: true
    left:
      - text: Cours
        menu:
          - text: Introduction
            href: cours/presentation.qmd
          - text: Décomposition en valeurs singulières
            href: cours/SVD.qmd
          - text: Analyse en composantes principales
            href: cours/ACP.qmd
          - text: Analyse factorielle des correspondances
            href: cours/AFC.qmd
          - text: Analyse des correspondances multiples
            href: cours/ACM.qmd
          - text: Analyse factorielle multiple
            href: cours/AFM.qmd
      - text: TD
        menu:
          - text: TD 1. ACP
            href: td/1_ACP/TD.qmd
          - text: TD 2. AFC/ACM
            href: td/2_ACM/TD.qmd
          - text: TD 3. AFM
            href: td/3_AFM/TD.qmd
      - text: TP
        menu:
          - text: TP 1. ACP
            href: tp/1_ACP/TP.qmd
          - text: TP 2. AFC/ACM
            href: tp/2_AFC-ACM/TP.qmd
      - text: Quarto
        menu:
          - text: Markdown
            href: tp/0_quarto/markdown.qmd
          - text: Quarto
            href: tp/0_quarto/quarto.qmd
      - text: Références
        href: resources.qmd
    right:
      - text: "{{<iconify simple-icons:moodle title='Moodle'>}}"
        href: https://moodle.utoulouse.fr/
        aria-label: Moodle
      - text: "{{< iconify simple-icons:github title='GitHub'>}}"
        href: https://github.com/bcharlier/KMAK7AC1
        aria-label: GitHub
format:
  html:
    theme: 
      - lux
      - assets/custom.scss
    grid:
      body-width: 1100px
    css:
      - assets/table.css
      - assets/print-clean.css
    include-in-header:
      - assets/unfold-panel.html
    html-math-method: katex
    number-sections: true
    
    code-fold: false
    code-tools:
      toggle: false
      source: false
    code-overflow: wrap
    highlight-style: github
    fig-align: center
    reference-location: margin
    citation-location: margin
    from: markdown+emoji
    toc: false
    #toc-location: right
    #toc-depth: 3

  revealjs:
    theme: assets/metropolis.scss
    css: assets/table.css
    default-image-extension: svg
    html-math-method:
      method: katex
    width: 1024
    height: 768
    slide-level: 2
    slide-number: true
    progress: true
    history: false
    toc: true
    toc-depth: 1
    code-line-numbers: false
    eval: true
    echo: true
    fig-align: center

execute:
  freeze: auto
  cache: false

knitr:
  opts_chunk:
    prompt: true
    message: false
    warning: false
    dev: svglite